sudo: required
services:
        - docker

before install:
        - docker build -t praveenkalasa1/docker-react -f Dockerfile.dev .

script:
        - docker run praveenkalasa1/docker-react npm run test -- --coverage
